language: node_js
node_js:
- 11.4.0
before_deploy: "npm install"
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: examples/build/
    github_token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: 'ermakov.1828@gmail.com'
    api_key: $NPM_TOKEN
    on:
      branch: master